# Generated by Django 2.0.1 on 2018-02-06 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordsys_name', models.CharField(max_length=255, verbose_name='Наименование Системы Координат')),
                ('coordsys_param', models.CharField(max_length=255, verbose_name='Параметры Системы координат')),
            ],
            options={
                'verbose_name': 'Система координат',
                'verbose_name_plural': 'Системы координат',
                'db_table': 'CoordSys',
            },
        ),
        migrations.CreateModel(
            name='PointBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=255, verbose_name='Название точки')),
                ('point_X', models.CharField(max_length=255, verbose_name='X')),
                ('point_Y', models.CharField(max_length=255, verbose_name='Y')),
                ('point_csid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geobase.CoordSys', verbose_name='Система координат')),
                ('point_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Координата точки',
                'verbose_name_plural': 'Координаты точек',
                'db_table': 'PointBase',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='Наименование Проекта')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'Project',
            },
        ),
        migrations.AddField(
            model_name='pointbase',
            name='point_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geobase.Project', verbose_name='Проект'),
        ),
    ]
